### ISSUE TITLE
README.md points to https://circleci.com/account/api that returns HTTP 404

### ISSUE THREAD

**Issue by alexeyhimself** [CircleCI-Public/circleci-config-generator#4]
**Steps to reproduce:**
1. Open https://github.com/CircleCI-Public/circleci-config-generator/blob/master/README.md
1. How-to use, step 4 has https://circleci.com/account/api

**Actual result:**
```
$ curl -I https://circleci.com/account/api
HTTP/1.1 404 Not Found
```
**Expected result:**
A working link 

(I don't know valid expected link for instruction. I found only parametrized one for my account: https://circleci.com/gh/<user>/<project>/edit#api - and not yet sure if it's that one mentioned in instruction)

**Comment by eddiewebb** [comment]
https://circleci.com/account/api is a valid UI page.   It should be visible so long as you are logged in to your account, otherwise unauthenticated attempts (like your curl command) will get a 404.
